### PR TITLE
Fix imports for scripting

### PR DESCRIPTION
**Pull request by dschick**
this PR updates the import statements in order to use kkcalc both in the gui and for scripting in python.
It also adds a script example.

### CODE REVIEW

**Comment by benajamin** [comment]
Thanks for the PR, I agree that this kind of tidying up is needed. I'll try to make some time to test it (and probably add some more documentation at the same time).

**Comment by dschick** [comment]
let me know, if you need help with that.
It is actually a pretty nice and neat tool.
Sometimes I prefer scripting over a gui, so this is why I brought this up.

Regarding the example, do you have some experimental data, that could be added to the repo for the example?
I could update the example accordingly.

I think it would be also a good idea, to transform the `data` and `kk` module into classes ...

**Comment by benajamin** [comment]
Yes, I have some experimental data that could be added for the example script.
I don't understand how the modules would work as classes (or why that is a good idea), as I am not much of a programmer, but I would be interested to hear more on the topic.

**Comment by dschick** [comment]
could you maybe send your data to me by email so I can add it to the PR?

> I don't understand how the modules would work as classes (or why that is a good idea)

Essentially you just wrap all your functions in the module into one or multiple classes.
On the first sight there might not be so many benefits, but you could avoid handing over so many function arguments all the time, as you could set some of them as properties of your `data` or `kk` objects.

If I have time I could come up with a separate PR for this, if you like.

> I am not much of a programme

The code works fairly nice and the function documentation is pretty well done. So don't underestimate yourself here :)

**Comment by dschick** [comment]
just added some experimental Fe L3 L2 data to the example and also plot the Henke data

**Comment by benajamin** [comment]
I finally got around to doing some work on kkcalc. The commits that I just pushed have fulfilled this pull request and so I will close it. While I have followed the spirit of your merge request, the code ended up being quite different. I think I have found the way to have the imports work correctly for all different types of usage. For the example, I applied your script to a polystyrene measurement that I had. Fe is not good for a simple example because XMCD breaks time reversal symmetry and so the KK-transform actually needs to be done a bit differently (resulting in a subtle energy-shift in the real-spectrum features).

**Comment by dschick** [comment]
Hi @benajamin 

Many thanks for continuing this project.
I will test the new code asap.

Could you tell me a bit more about the Fe issues with the XMCD?
We could also have a dedicated issue on that.

Best

Daniel

**Comment by benajamin** [comment]
Yes, let's not post to a dead thread. I have opened discussion in issue #3

**Pull request closed without merging**
